import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import { Flex } from '@chakra-ui/react'

const Banner = ({purpose})=>(
  <Flex flexWrap='wrap' justifyContent='center' alignItems='center' m='10'>
    {purpose}
  </Flex>
)

export default function Home() {
  return (
    <>
      <Head>
        <title>RealeState</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner purpose={'For Sale'}/>
        <Banner purpose={'For Rent'}/>
      </main>
    </>
  )
}
