import Head from 'next/head'
import Image from 'next/image'
import { Flex } from '@chakra-ui/react'
import { Box, Text } from '@chakra-ui/layout'
import { Button } from '@chakra-ui/button'
import Link from 'next/link'

const Banner = ({purpose,title1,title2,desc1,desc2,imageUrl,linkName,buttonText})=>(
  <Flex flexWrap='wrap' justifyContent='center' alignItems='center' m='10'>
    <Image src={imageUrl} width={500} height={300} alt='banner'/>
    <Box p='5'>
      <Text color='gray.500' fontSize='sm' fontWeight='medium'>{purpose}</Text>
      <Text fontSize='3xl' fontWeight='bold'>{title1}<br/>{title2}</Text>
      <Text fontSize='lg' paddingTop='3' paddingBottom='3' color='gray.700'>{desc1}<br/>{desc2}</Text>
      <Button fontSize='xl' bg='blue.300' color='white'>
        <Link href={linkName}>{buttonText}</Link>
      </Button>
    </Box>
  </Flex>
)

export default function Home() {
  return (
    <>
      <Head>
        <title>Real Estate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner purpose='RENT A HOME' title1='Rental Homes for' title2='Everyone' desc1='Explore Apartments, Villas, Homes' desc2='and more' buttonText='Explore Renting' linkName='/search?purpose=for-rent' imageUrl='https://bayut-production.s3.eu-central-1.amazonaws.com/image/145426814/33973352624c48628e41f2ec460faba4'/>
        <Banner purpose='BUY A HOME' title1='Find, Buy & Own Your' title2='Dream Home' desc1='Explore Apartments, Villas, Homes' desc2='and more' buttonText='Explore Renting' linkName='/search?purpose=for-rent' imageUrl='https://bayut-production.s3.eu-central-1.amazonaws.com/image/145426814/33973352624c48628e41f2ec460faba4'/>
      </main>
    </>
  )
}
